import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Comic.module.css';
import Comic from '../components/comic';
import { Filters } from '../components/filters/filter_index';
import { fetchData } from '../hooks/fetchData';
import { ComicResult } from '../../types';

export default function Home() {
	const slides = {
		display: 'grid',
		gridTemplateColumns: 'repeat(auto-fit, minmax(183px, 1fr))',
		gridGap: '30px 20px',
		paddingInline: '10px',
	};

	const [url, setUrl] = useState('/api/comics');

	const { isLoading, data, serverError } = fetchData(url);

	// url is being listened to in the fetchData file
	const updateCall = (query:string) => {
		setUrl(`/api/comics?${query}`);
	};

	return (
		<>
			<Head>
				<title>Comic Cards</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Filters isLoading={isLoading} updateCall={updateCall} />
			<div data-testid='grid' style={slides} className={styles.slides}>
				{isLoading ? (
					<span>Loading...</span>
				) : serverError ? (
					<span>Error in fetching data...</span>
				) : (
					data.length ? data.map((comic: ComicResult) => <Comic key={comic.id} comic={comic} />) : <h3>No results</h3>
				)}
			</div>
		</>
	);
}
