import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Comic.module.css';
import Comics from '../components/comics/index';

export default function Home() {
	return (
		<>
			<Head>
				<title>Comic Cards</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			< Comics />
		</>
	);
}
