import Head from 'next/head';
import styles from '@/styles/Comic.module.css';
import Comic from '../components/comic/Comic'

import staticData from '../data/comics.json';


export default function Home() {
	const slides = {
		display: "grid",
		gridTemplateColumns: "repeat(auto-fit, minmax(183px, 1fr))",
		gridGap: "30px 20px",
		paddingInline: "10px",
		height: "100%"
	}
	return (
		<>
			<Head>
				<title>Comic Cards</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div style={slides} className={styles.slides}>
				{staticData?.map((content, key) => {
					return (
						<Comic key={key} content={content}/>
					);
				})}
			</div>
		</>
	);
}
